apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aligner-prod-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '1'
spec:
  project: default
  source:
    repoURL: https://github.com/Nexters/ALIGNER-PLATFORM.git
    targetRevision: main
    path: gitops/infrastructure/configs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
