apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aligner-prod-controllers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  source:
    repoURL: https://github.com/Nexters/ALIGNER-PLATFORM.git
    targetRevision: main
    path: gitops/infrastructure/controllers
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
