apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: aligner-db-daily
  namespace: aligner-data
spec:
  schedule: "0 0 19 * * *"
  backupOwnerReference: self
  cluster:
    name: aligner-db
  immediate: false
  method: barmanObjectStore
