apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cloudnative-pg
  - alloy
  - tailscale-operator.application.yaml
  - tailscale-argocd-ui.application.yaml
  - gateway-api
  - cert-manager
  - traefik
