apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-https-redirect
  namespace: traefik
spec:
  parentRefs:
    - name: platform-gateway
      sectionName: http
  hostnames:
    - api.aligneryoga.com
    - aligneryoga.com
    - dev-api.aligneryoga.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 308
